"""initial schema

Revision ID: 1366ef359569
Revises: 
Create Date: 2026-08-07 19:04:34.289510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1366ef359569'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('company_id', name=op.f('pk_companies')),
    sa.UniqueConstraint('ticker', name=op.f('uq_companies_ticker'))
    )
    op.create_table('organizations',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tier', sa.Enum('FREE', 'PRO', 'ENTERPRISE', name='org_tier'), nullable=False),
    sa.PrimaryKeyConstraint('org_id', name=op.f('pk_organizations'))
    )
    op.create_table('documents',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('FORM_10K', 'FORM_10Q', 'EARNINGS_TRANSCRIPT', 'INVESTOR_DECK', name='document_type'), nullable=False),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('upload_date', sa.Date(), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.CheckConstraint('fiscal_quarter IS NULL OR fiscal_quarter BETWEEN 1 AND 4', name=op.f('ck_documents_fiscal_quarter_range')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name=op.f('fk_documents_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_company_id'), 'documents', ['company_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.Enum('ANALYST', 'ADMIN', name='user_role'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id'], name=op.f('fk_users_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_table('conversations',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_conversations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id', name=op.f('pk_conversations'))
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_type', sa.Enum('NARRATIVE', 'TABLE', 'FOOTNOTE', name='chunk_type'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('embedding_vector_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], name=op.f('fk_document_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id', name=op.f('pk_document_chunks')),
    sa.UniqueConstraint('document_id', 'page_number', 'chunk_index', name='uq_document_chunks_document_id_page_number_chunk_index'),
    sa.UniqueConstraint('embedding_vector_id', name=op.f('uq_document_chunks_embedding_vector_id'))
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_table('queries',
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('reformulated_query_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], name=op.f('fk_queries_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('query_id', name=op.f('pk_queries'))
    )
    op.create_index(op.f('ix_queries_conversation_id'), 'queries', ['conversation_id'], unique=False)
    op.create_table('table_data',
    sa.Column('table_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('raw_table_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('column_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.chunk_id'], name=op.f('fk_table_data_chunk_id_document_chunks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('table_id', name=op.f('pk_table_data')),
    sa.UniqueConstraint('chunk_id', name=op.f('uq_table_data_chunk_id'))
    )
    op.create_table('answers',
    sa.Column('answer_id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence_score >= 0 AND confidence_score <= 1', name=op.f('ck_answers_confidence_score_range')),
    sa.ForeignKeyConstraint(['query_id'], ['queries.query_id'], name=op.f('fk_answers_query_id_queries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('answer_id', name=op.f('pk_answers')),
    sa.UniqueConstraint('query_id', name=op.f('uq_answers_query_id'))
    )
    op.create_table('eval_results',
    sa.Column('eval_id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('retrieval_precision', sa.Float(), nullable=False),
    sa.Column('groundedness_score', sa.Float(), nullable=False),
    sa.Column('flagged_by_human', sa.Boolean(), nullable=False),
    sa.CheckConstraint('groundedness_score >= 0 AND groundedness_score <= 1', name=op.f('ck_eval_results_groundedness_score_range')),
    sa.CheckConstraint('retrieval_precision >= 0 AND retrieval_precision <= 1', name=op.f('ck_eval_results_retrieval_precision_range')),
    sa.ForeignKeyConstraint(['query_id'], ['queries.query_id'], name=op.f('fk_eval_results_query_id_queries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('eval_id', name=op.f('pk_eval_results')),
    sa.UniqueConstraint('query_id', name=op.f('uq_eval_results_query_id'))
    )
    op.create_table('citations',
    sa.Column('citation_id', sa.UUID(), nullable=False),
    sa.Column('answer_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('exact_location', sa.String(length=255), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.answer_id'], name=op.f('fk_citations_answer_id_answers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.chunk_id'], name=op.f('fk_citations_chunk_id_document_chunks')),
    sa.PrimaryKeyConstraint('citation_id', name=op.f('pk_citations'))
    )
    op.create_index(op.f('ix_citations_answer_id'), 'citations', ['answer_id'], unique=False)
    op.create_index(op.f('ix_citations_chunk_id'), 'citations', ['chunk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_citations_chunk_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_answer_id'), table_name='citations')
    op.drop_table('citations')
    op.drop_table('eval_results')
    op.drop_table('answers')
    op.drop_table('table_data')
    op.drop_index(op.f('ix_queries_conversation_id'), table_name='queries')
    op.drop_table('queries')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_documents_company_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('organizations')
    op.drop_table('companies')
    # ### end Alembic commands ###
