"""add document title and status

Revision ID: 8c520544e49c
Revises: e0bad18df9c5
Create Date: 2026-08-08 18:00:32.147190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c520544e49c'
down_revision: Union[str, Sequence[str], None] = 'e0bad18df9c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


document_status_enum = sa.Enum(
    'PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='document_status'
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('title', sa.String(length=512), nullable=False))
    # `op.add_column` (unlike `op.create_table`) does not implicitly CREATE
    # the Postgres ENUM type for a new Enum column -- that only happens
    # automatically for enums declared inline on a brand-new table (see the
    # 1366ef359569 initial migration). Autogenerate doesn't add this call by
    # itself; it's a hand adjustment on top of the raw autogenerate output.
    document_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('documents', sa.Column('status', document_status_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'status')
    document_status_enum.drop(op.get_bind(), checkfirst=True)
    op.drop_column('documents', 'title')
    # ### end Alembic commands ###
